AllCops:
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/EmptyLinesAroundBlockBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false
